Fix issue #5
matsuyoshi30/gitsu pull request #10
Opened 2021-04-02 17:18 UTC by Techassi

This fixes #5 

This PR fixes multiple things:

#### Option to modify existing users

```shell
Use the arrow keys to navigate: ↓ ↑ → ←
? Select action:
    Select git user
    Add new git user
    Delete git user
  > Modify git user
```

Following this you can select the user to modify

```shell
? Select git user:
  > Dog <lazy@dog.com>
    [foo] Foo <bar@baz.com>
    [rick] Rick <rick@astley.com>
```

You are then guided through updating each user option (name, email, GPG key ID and alias). Leaving an option empty results in no change for this specific option.

#### Support for aliases

When adding a new user you can specify an alias. This allows you to execute `gitsu <alias>` which immediatly sets the git user.

#### Misc

This commit also adds a default `.gitignore` for Go projects (See [here](https://github.com/github/gitignore/blob/master/Go.gitignore))

I seperated the `git config` commands into their own file and combined the 3 commands into one function called `SetGitConfig`. This cuts down on complexity in the gitsu commands and follows DRY.

2021-04-05 13:45 UTC, Techassi commented
Rebased changes from #8 and #9 into this branch. Now able to merge

2021-04-07 19:04 UTC, Techassi commented
Any update on this PR @matsuyoshi30 ?

2021-04-08 04:38 UTC, matsuyoshi30 commented
@Techassi Sorry for the delay. I'll take a look until this weekend :)

2021-04-09 14:01 UTC, matsuyoshi30 requested changes

2021-04-09 14:01 UTC, matsuyoshi30 commented on main.go
>  		Items:  []string{sel, add, del},
I think it's necessary that `mod` is added into `Items`.

2021-04-09 16:44 UTC, Techassi commented on main.go
>  		Items:  []string{sel, add, del},
You are 100 percent right. These changes slipped by me while merging the changes from #8 and #9. Will re-add immediately.

2021-04-09 16:58 UTC, Techassi commented on main.go
>  		Items:  []string{sel, add, del},
Updated - marking as resolved.

2021-04-13 16:29 UTC, Techassi commented
Were you able to look over the change you requested?

2021-04-14 08:59 UTC, matsuyoshi30 approved these changes

2021-04-14 09:00 UTC, matsuyoshi30 commented
@Techassi Sorry for the delay again, and thanks for your contribution!

2021-04-14 09:00 UTC, merged

2021-04-14 09:07 UTC, Techassi commented
No worries! You are welcome...